variables:
  GIT_STRATEGY: clone

stages:
  - scan_and_wait

scan:
  stage: scan_and_wait
  tags:
    - secret-scanning
  image:
    name: mega-docker.artifactory.developers.mega.co.nz:8443/gitleaks:v8.18.2-mega-1.0
    entrypoint: [""]
  script:
    - gitleaks detect -v --redact -c .gitleaks/gitleaks.toml

wait_for_jenkins:
  stage: scan_and_wait
  script:
    - echo "Waiting for Jenkins..."
    - sleep 500
